apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymovies-hd
  labels:
    app: mymovies-hd
    version: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mymovies-hd
  template:
    metadata:
      labels:
        app: mymovies-hd
        version: test
    spec:
      containers:
      - name: mymovies-hd
        image: registry.meyacrew.com:5050/my-movies/front-mymovies:test
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: __ENVIRONMENT__
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      imagePullSecrets:
      - name: registry-secret